id: IEB70FEEB
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-05T19:51:27.276926'
last_modified: '2022-06-05T19:51:27.276936'
parser: null
source_metadata:
  title: Samten Lingpa Series
  language: bo
  description: 'Texts by and about Samten Lingpa Trinle Drodül Lerab Dewa Tsal (bsam
    gtan gling pa ''phrin las ''gro ''dul las rab bde ba rtsal, b. 1871?), who was
    active in the nineteenth century:'
  volume:
    fBD02:
      title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
      base_file: fBD02.txt
      order: 1
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
